version: 1.2
workflows:
   - name: "STAR-build-index"
     subclass: WDL
     primaryDescriptorPath: /workflows/star-build-index.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
   - name: "Align-quantify-repeats"
     subclass: WDL
     primaryDescriptorPath: /workflows/align-quantify-repeats.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
   - name: "Align-quantify-repeats-chromatin"
     subclass: WDL
     primaryDescriptorPath: /workflows/align-quantify-repeats-chromatin.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
   - name: "Align-quantify-repeats-scatter"
     subclass: WDL
     primaryDescriptorPath: /workflows/align-quantify-repeats-scatter.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - scatter-inputs
         tags:
             - /.*/